### ISSUE TITLE
Github API v4 offers GraphQL

### ISSUE THREAD

**Issue by paazmaya** [paazmaya/maezato#75]
How about reducing the amount of API calls into one by using GraphQL?

https://github.com/octokit/graphql.js/

**Comment by Presto412** [comment]
Willing to work on this. Which API calls do you intend to simplify?

**Comment by paazmaya** [comment]
Combine all into one and only to get the relevant info that is being used.

**Comment by paazmaya** [comment]
Let me know if you @Presto412 need any pointers on this and once you have initial PR, we can discuss more via that

**Comment by Presto412** [comment]
This calls for making a string graphql query builder, right? Based on the command line arguments, the query is constructed and sent as a request. With some defaulting structures set.

**Comment by Presto412** [comment]
I've done most of it, however, the graphql API doesn't seem to provide the source of a fork. If you have any leads let me know. Else, I'll submit the PR.

**Comment by paazmaya** [comment]
Can you submit the PR already, so I can have a look and comment there?

**Comment by paazmaya** [comment]
Merged the PR #78 and will continue working on it in `master`. In case you want to help, please open another PR.

**Comment by paazmaya** [comment]
Version 0.10.0 release now, which includes this
